services:
  nginx:
    image: nginx:alpine
    container_name: dpm-core-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./local.dpmcore.o-r.kr.pem:/etc/ssl/certs/local.dpmcore.o-r.kr.pem
      - ./local.dpmcore.o-r.kr-key.pem:/etc/ssl/private/local.dpmcore.o-r.kr-key.pem
    networks:
      - dpm-network
  
  mysql:
    image: mysql:8.0
    container_name: dpm-core-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dpm_core
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dpm-network

volumes:
  mysql-data:

networks:
  dpm-network:
    driver: bridge
