services:
  nginx:
    image: nginx:alpine
    container_name: dpm-core-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./local.depromeet-core.shop.pem:/etc/ssl/certs/local.depromeet-core.shop.pem
      - ./local.depromeet-core.shop-key.pem:/etc/ssl/private/local.depromeet-core.shop-key.pem
    