name: Deploy App with Vercel

on:
  workflow_dispatch:
    inputs:
      stage_choice:
        description: 배포 유형
        type: choice
        options:
          - production
          - preview
      app:
        description: 배포할 앱
        required: true
        type: choice
        options:
          - admin
          - client
          - all

run-name: '${{ inputs.stage_choice }}: ${{ github.actor }} runs workflow to deploy ${{ inputs.app }}'

jobs:
  deploy:
    uses: './.github/workflows/deploy-vercel.yml'
    with:
      stage: ${{ inputs.stage_choice }}
      app: ${{ inputs.app == 'all' && '["admin","client"]' || format('["{0}"]', inputs.app) }}
    secrets: inherit
