name: Deploy App with Vercel

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 배포한 사용자
        required: true
        type: string
      stage_choice:
        description: 배포 유형
        type: choice
        options:
          - production
          - develop
      app:
        description: 배포할 앱
        required: true
        type: choice
        options:
          - admin
          - client
          - all

run-name: '${{inputs.user_name}} runs workflow for ${{inputs.stage_choice}} deploy ${{inputs.app}}'

jobs:
  deploy:
    uses: './.github/workflows/deploy-vercel.yml'
    with:
      user_name: ${{ inputs.user_name }}
      stage: ${{ inputs.stage_choice }}
      app: ${{ inputs.app == 'all' && '["admin","client"]' || format('["{0}"]', inputs.app) }}
    secrets: inherit
